### ISSUE TITLE
How to use .md file

### ISSUE THREAD

**Issue by manishlok** [sinnbeck/markdom#1]
Hi, thanks for this great package. It is helpful.
I am a newbie so my question is can we pass a markdown file or .md file url in controller.
Waiting for your reply !

**Comment by sinnbeck** [comment]
Great to hear. Is the md file local or on another server?

I assume you want to render it inside a view? Something like hvis would probably be the easiest way. If it does not fit your use case, let me know. Maybe Markdom needs a new feature I haven't thought of yet 
```
public function show()
{
    $markdown = file _get_contents($pathToFile);
    return view('myview', compact('markdown'));
}

**Comment by manishlok** [comment]
Thank you so much. It works now
