### ISSUE TITLE
Anchor tags

### ISSUE THREAD

**Issue by andrepolo** [sinnbeck/markdom#2]
Is there a way to automatically add (hidden) anchor tags to h1, h2 etc. Would be useful to create a navigation. Markdown is often used for Readme files or documentations.

**Comment by sinnbeck** [comment]
Not currently but that could be a nice addition. If you have any ideas for an api, let me know (or create a pr)

Are you using it to generate documentation?

**Comment by andrepolo** [comment]
Hi René,

see this commit: https://github.com/andrepolo/markdom/commit/958b523ebd5d6dbfef32b28b17703014f4e74b2c <https://github.com/andrepolo/markdom/commit/958b523ebd5d6dbfef32b28b17703014f4e74b2c>

The changes are not persisted in the dom. Don't know why. When ich dump $element in `addAnchorTags` it’s there, but not in the test.
Maybe you have an idea.

Greetings, André

**Comment by sinnbeck** [comment]
I would have assumed that would work. Feel free to push it and I will help debugging it.

And two things I would like added. Slug delimiter. People might like to use something other than default. And position (before, inside or after). You might like the a tag inside the h tag, for easy styling

**Comment by sinnbeck** [comment]
And an idea for the structure of the config, to make it feel like it belongs together
```
'anchor_tags' [
    'enabled' => env('MARKDOM_ADD_ANCHORS', true),
    'elements' => [
        'h1',
        'h2',
        'h3'
    ],
    'slug_delimiter = '-',
    'position' => 'before',
];

**Comment by sinnbeck** [comment]
Btw, I posted the solution in your commit. Looking forward to your PR :)

**Comment by andrepolo** [comment]
Hey dude, sorry for late reply. Was working all day.

Thanx for the comment on the commit. What about not putting it before the a tag, but wrap the anchor around the H tag?

Where are you located btw.?

**Comment by andrepolo** [comment]
Adjusted the method according to your suggested config. Still works fine but not in the test :-(

**Comment by sinnbeck** [comment]
No worries. I figured you wanted to create the feature yourself. 

Create a pull request with what you have and I will help get it working. I like the flexibility of letting the user choose where to add it. I feel confident that we can make it work.

I live in Denmark.

**Comment by andrepolo** [comment]
Just created a PR. Let me know, what you wanna do with it.

Im from Leipzig, Germany. Not too far away :-)

**Comment by sinnbeck** [comment]
Yeah our southern neighbors :+1: 

Are you working on documentation for something? My next project is actually related to that

**Comment by andrepolo** [comment]
WTF? All (my) tests are failing on Github :-( it’s all green locally. See screenshot. Can you sort out what’s wrong?

**Comment by andrepolo** [comment]
Well, it’s about the ul. I think i’m going to remove it. It’s not needed in the test anyway. Hope you’re fine with it?	

It’s all green again, im going to bed. Cheerio!

**Comment by sinnbeck** [comment]
Yeah I was struggling with that as well, yesterday. Seems that the dom parser works a little different in the github action. I fixed mine by forcing indents in the test. 

I am considering if the package should also make proper indents automatically. But I fear that it could cause problems. Minifying the HTML could also be a solution, but might make it hard to read :)

Thanks for the PR! I will get it merged and published as soon as possible.

**Comment by sinnbeck** [comment]
@andrepolo Shouldn't it be `id="slug"` instead of `name="slug"` ? I believe that name has been deprecated in HTML5

![image](https://user-images.githubusercontent.com/13980140/98792612-0c05a680-2407-11eb-9d5a-177dc004e738.png)

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

**Comment by sinnbeck** [comment]
I am working a bit on the config API and how id + href are added

1. Add `href` to all <a /> tags (allow disabling)
2. Allow user to specify if the `id` goes on the element or the `a`. As an example, the official laravel docs have `id` on `<h*>` and `href` on the `<a />` tag.
3. Simply drop the a tag if id is on the element and href is disabled (I cannot see any reason to have it there if it is empty)

Example
```
'anchor_tags' => [
        'enabled' => env('MARKDOM_ADD_ANCHORS', false),

        'elements' => [
            'h1',
            'h2',
            'h3',
        ],

        'add_id_to' => 'element',

        'disable_href' => false,

        'slug_delimiter' => '-',

        'position' => 'before',
    ],

**Comment by andrepolo** [comment]
Hi René,

feel free to modify it to your needs.

W3.org <http://w3.org/> is listing neither ’name' nor ‚id‘ as valid attributes for an anchor tag :-( https://www.w3schools.com/tags/tag_a.asp <https://www.w3schools.com/tags/tag_a.asp>. Maybe you do right when you add support to create an id for the element instead of an anchor tag. Im a backend developer. Stopped doing html stuff years ago :-D

**Comment by sinnbeck** [comment]
Released :)

**Comment by andrepolo** [comment]
Great deal mate, works fine for me, cheers!

**Comment by andrepolo** [comment]
Next big thing would be to automatically generate a navigation from the markdown. Grabbing the ids from defined tags, such as h-tags for example, and generate an unordered list of menu-items you could use where you show the rendered markdown. You could even use the classes for this menu that are defined in the config.

Tell me what you think,
André
