### ISSUE TITLE
Is there a way to escape underscore?

### ISSUE THREAD

**Issue by ivqonsanada** [sinnbeck/markdom#5]
I tried something like:
```php
Markdom::toHtml('do_something bla bla bla')
``` 
But then it converted to `do<em>something bla bla bla</em>` which will looks like do<em>something bla bla bla</em>.

Been tried to using backslash like this:
```php
Markdom::toHtml('do\_something bla bla bla')
``` 
It converted as is `do\_something bla bla bla` instead of what I expect it to be `do_something bla bla bla`

Edit:
I tried change the configurations parser
`use_underscore` and `enable_em` to false but still the same. Am I missing something?

**Comment by sinnbeck** [comment]
Does it work if you disable em in the config?

```
'enable_emphasis' => false,

**Comment by ivqonsanada** [comment]
> Does it work if you disable em in the config?
> 
> ```
> 'enable_emphasis' => false,
> ```

Unfortunately, its not.
I did this:
```php
'commonmark' => [
        'enable_emphasis' => false,
        'enable_em' => false,
        'use_underscore' => false,
        ...
]
```
I do check if the config working properly by inject a class in `'classes'` and it does work. 

I then tried to change other option in `'commonmark'` like `enable_strong` and `use_asterisk` and all of that doesn't seem to work at all. There may be a problem in the `commonmark` options(?)

**Comment by sinnbeck** [comment]
That is strange. I just gave it a try myself on a project that uses Markdom, and it seems to work just fine

```
Sinnbeck\Markdom\Facades\Markdom::toHtml('do_something bla bla bla');
```
Becomes
```
<p class="py-2">do_something bla bla bla</p>
```
This has been tested using `php artisan tinker`

I even wrote a test directly in markdom to test it out and it outputs `<p>do_something bla bla bla</p>`
This uses the default config file that ships with Markdom

```
test('it can handles underscores', function () {
    $converter = app('markdom');

    $markdown =
        <<<MARKDOWN
do_something bla bla bla
MARKDOWN;

    assertMatchesTextSnapshot($converter->toHtml($markdown));
});
```
Any chance you can create a tiny laravel project to show off the issue?

**Comment by ivqonsanada** [comment]
Ahh, sorry for the effort you made. 
I just realized that the problems comes from another layer in the Frontend that still convert the converted html as if there still a markdown in there. Problems solved in such a shame on me.

Anyway, thank you for making this library, Sinnbeck. It such a help for automate class injection to the markdown. I really enjoy the flexibility of the query injection way. I try TailwindCss for my current project, and it such a good way to do styling. :)

**Comment by sinnbeck** [comment]
No worries. Just happy to hear that you worked it out :)

And I actually made it as I had to style some markdown with tailwind, and I got annoyed with having to use a css file with tons of `@apply` rules
